# Generated by Django 3.2.7 on 2021-11-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('belum_vaksin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EfekSamping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('nik', models.BigIntegerField()),
                ('no_hp', models.BigIntegerField()),
                ('alamat', models.TextField()),
                ('vaksin', models.CharField(max_length=20)),
                ('gejala', models.TextField()),
                ('token', models.CharField(default='', max_length=5)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belum_vaksin.pesertavaksin')),
            ],
        ),
    ]
