# Generated by Django 3.2.7 on 2021-11-06 01:43

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jadwal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesertaVaksin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waktu', models.DateField(default=datetime.date.today, verbose_name='Waktu')),
                ('tempat_pelaksanaan', models.CharField(max_length=100)),
                ('jenis_vaksin', models.CharField(max_length=20)),
                ('nama_peserta', models.TextField(default='', max_length=100)),
                ('nik', models.TextField(default='', max_length=100)),
                ('no_telp', models.TextField(default='', max_length=100)),
                ('token', models.TextField(default='8MbDF', max_length=5)),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jadwal.sesivaksinasi')),
            ],
        ),
    ]
