# Generated by Django 3.2.7 on 2021-11-06 01:43

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SesiVaksinasi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waktu', models.DateField(default=datetime.date.today, verbose_name='Waktu')),
                ('tempat_pelaksanaan', models.CharField(max_length=100)),
                ('jenis_vaksin', models.CharField(max_length=20)),
                ('kuota', models.IntegerField(default=0)),
            ],
        ),
    ]
